server:
  error:
    include-message: always
    include-binding-errors: always
    path: /error

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: # mysql-username
    password: # mysql-specific-user-password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret: 
          google:
            client-id: 
            client-secret: 

  mail:
    host: smtp.gmail.com # or maildev
    port: 587
    username: #your-gmail-id or maildev-id
    password: 
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          timeout: 3000
